export const toolSlugs: Record<string, { title: string; description: string; tag: string }> = {
  'big-three-meaning': { title: 'Big Three Meaning Tool', description: 'Interpret your Sun, Moon and Rising signs together as identity, emotional needs and outer style.', tag: 'Advanced Astrology' },
  'planet-sign-meaning': { title: 'Planet Sign Meaning Tool', description: 'Choose a planet and zodiac sign to generate a deeper interpretation of that placement.', tag: 'Advanced Astrology' },
  'moon-sign-meaning': { title: 'Moon Sign Meaning Tool', description: 'Explore emotional needs, comfort patterns, stress responses and self-care themes by Moon sign.', tag: 'Advanced Astrology' },
  'venus-sign-love-style': { title: 'Venus Sign Love Style Tool', description: 'Understand attraction, affection, relationship needs and love blind spots by Venus sign.', tag: 'Advanced Astrology' },
  'mars-sign-action-style': { title: 'Mars Sign Action Style Tool', description: 'Explore motivation, conflict style, ambition, desire and stress reactions by Mars sign.', tag: 'Advanced Astrology' },
  'mercury-sign-communication': { title: 'Mercury Sign Communication Tool', description: 'Understand thinking style, communication habits, learning rhythm by Mercury sign.', tag: 'Advanced Astrology' },
  'aspect-meaning': { title: 'Aspect Meaning Tool', description: 'Understand conjunctions, squares, trines, sextiles and oppositions between two signs.', tag: 'Advanced Astrology' },
  'planet-in-house': { title: 'Planet in House Meaning Tool', description: 'Learn what a planet means when placed in each of the twelve astrological houses.', tag: 'Advanced Astrology' },
  'rising-sign-estimator': { title: 'Rising Sign Estimator', description: 'A simplified educational rising-sign style prompt based on approximate birth time.', tag: 'Advanced Astrology' },
  'birth-chart-checklist': { title: 'Birth Chart Reading Checklist', description: 'A practical step-by-step checklist for reading a natal chart in the right order.', tag: 'Guides' },
  'zodiac-calculator': { title: 'Zodiac Sign Calculator', description: 'Enter your birth date to find your zodiac sign with a detailed personality profile.', tag: 'Astrology Tools' },
  'moon-phase': { title: 'Moon Phase Birthday Tool', description: 'Find the moon phase on your birthday and what it reveals about your emotional nature.', tag: 'Lucky Tools' },
  'daily-horoscope': { title: 'Daily Horoscope Generator', description: 'Generate a light daily reflection prompt based on your zodiac sign.', tag: 'Astrology Tools' },
  'horoscope-2026': { title: '2026 Horoscope Tool', description: 'Explore a yearly reflection theme by zodiac sign for 2026.', tag: 'Astrology Tools' },
  'compatibility': { title: 'Zodiac Compatibility Checker', description: 'Check astrological compatibility between any two zodiac signs with detailed analysis.', tag: 'Compatibility' },
  'love-compatibility': { title: 'Love Compatibility Test', description: 'Explore romantic compatibility between two signs with love-specific insights.', tag: 'Compatibility' },
  'friendship-compatibility': { title: 'Friendship Compatibility Calculator', description: 'Understand platonic friendship dynamics between any two zodiac signs.', tag: 'Compatibility' },
  'life-path': { title: 'Life Path Number Calculator', description: 'Calculate your numerology life path number from your birth date.', tag: 'Numerology' },
  'name-numerology': { title: 'Name Numerology Calculator', description: 'Calculate the numerology vibration of any name using Pythagorean method.', tag: 'Numerology' },
  'personal-year': { title: 'Personal Year Calculator', description: 'Calculate a numerology personal year theme from your birth date.', tag: 'Numerology' },
  'angel-number': { title: 'Angel Number Meaning Tool', description: 'Look up a symbolic meaning for repeated numbers you keep seeing.', tag: 'Numerology' },
  'chinese-zodiac': { title: 'Chinese Zodiac Calculator', description: 'Find your Chinese zodiac animal, traits, and compatibility from your birth year.', tag: 'Chinese Zodiac Tools' },
  'five-elements': { title: 'Five Elements Calculator', description: 'Explore a five-element personality theme from your Chinese zodiac birth year.', tag: 'Chinese Zodiac Tools' },
  'lucky-color': { title: 'Lucky Color Calculator', description: 'Get a symbolic color palette for focus, calm and confidence based on your zodiac sign.', tag: 'Lucky Tools' },
  'lucky-number': { title: 'Lucky Number Calculator', description: 'Find a playful lucky number and reflection theme based on your zodiac sign.', tag: 'Lucky Tools' },
  'birthday-personality': { title: 'Birthday Personality Calculator', description: 'Turn a birthday into a gentle personality reflection based on zodiac sign.', tag: 'Personality Tools' },
  'career-personality': { title: 'Career Personality Calculator', description: 'Get career style prompts from personality inputs based on your zodiac sign.', tag: 'Personality Tools' },
  'zodiac-money-style': { title: 'Zodiac Money Style Calculator', description: 'Reflect on spending, saving and comfort patterns by zodiac sign.', tag: 'Personality Tools' },
  'birth-time-unknown': { title: 'Birth Time Unknown Guide', description: 'Learn what you can and cannot read accurately when birth time is unknown.', tag: 'Personality Tools' },
  'yes-no-tarot': { title: 'Yes or No Tarot Picker', description: 'Pick a symbolic card and receive a yes/no prompt for self-reflection.', tag: 'Tarot Tools' },
};

export const articleSlugs: Record<string, { title: string; description: string; tag: string }> = {
  'big-three-guide': { title: 'Big Three Astrology Guide: Sun, Moon and Rising', description: 'Understand how Sun, Moon and Rising signs work together in a birth chart.', tag: 'Guide' },
  'planet-sign-placements': { title: 'Planet Sign Placements Guide', description: 'Learn what it means when a planet is in a zodiac sign with detailed interpretations.', tag: 'Guide' },
  'astrology-aspects-guide': { title: 'Astrology Aspects Beginner Guide', description: 'Understand conjunctions, squares, trines, sextiles and oppositions.', tag: 'Guide' },
  'astrology-houses-guide': { title: 'Astrology Houses Beginner Guide', description: 'Learn the 12 houses and what life areas they represent.', tag: 'Guide' },
  'zodiac-signs-guide': { title: 'Zodiac Sign Dates and Meanings', description: 'A clear guide to the 12 zodiac signs, dates, elements and practical meanings.', tag: 'Reference' },
  'astrology-beginners-guide': { title: 'The Beginner Guide to Astrology', description: 'Everything you need to know to start understanding astrology.', tag: 'Beginner' },
  'life-path-meanings': { title: 'Life Path Number Meanings', description: 'Detailed guide to all life path numbers in numerology and their meanings.', tag: 'Numerology' },
  'chinese-zodiac-guide': { title: 'Chinese Zodiac for Global Readers', description: 'Complete guide to the Chinese zodiac system with animal traits and compatibility.', tag: 'Reference' },
  'moon-sign-guide': { title: 'Moon Sign Complete Guide', description: 'Understanding your emotional self through Moon sign astrology.', tag: 'Guide' },
  'venus-sign-love-guide': { title: 'Venus Sign Love and Attraction Guide', description: 'How your Venus sign shapes love style and attraction patterns.', tag: 'Love & Relationships' },
  'mars-sign-motivation-guide': { title: 'Mars Sign Motivation and Action Guide', description: 'How Mars sign drives motivation, ambition, and conflict style.', tag: 'Guide' },
  'mercury-sign-communication-guide': { title: 'Mercury Sign Communication and Thinking Guide', description: 'How Mercury sign shapes thinking and communication styles.', tag: 'Guide' },
  'zodiac-compatibility-guide': { title: 'Zodiac Compatibility Complete Guide', description: 'Element compatibility, modality patterns, and full compatibility table.', tag: 'Compatibility' },
  'numerology-beginners-guide': { title: 'Numerology for Beginners: A Complete Guide', description: 'History, systems, core numbers, and practical applications of numerology.', tag: 'Numerology' },
  'rising-sign-guide': { title: 'Rising Sign (Ascendant) Complete Guide', description: 'What the Rising sign is, how it affects appearance and first impressions.', tag: 'Guide' },
  'angel-numbers-guide': { title: 'Angel Numbers Complete Guide', description: 'Meanings of common angel number sequences and how to interpret them.', tag: 'Numerology' },
  'chinese-five-elements-guide': { title: 'Chinese Five Elements (Wu Xing) Complete Guide', description: 'The Five Elements theory, generating and overcoming cycles.', tag: 'Reference' },
  'birth-chart-reading-guide': { title: 'Birth Chart Reading for Beginners', description: 'What a birth chart is, what you need, and step-by-step reading order.', tag: 'Beginner' },
  'fire-signs-guide': { title: 'Fire Signs Complete Guide: Aries, Leo, Sagittarius', description: 'Understand the Fire element with detailed profiles of Aries, Leo, and Sagittarius.', tag: 'Element Guide' },
  'earth-signs-guide': { title: 'Earth Signs Complete Guide: Taurus, Virgo, Capricorn', description: 'Explore the Earth element with detailed profiles of Taurus, Virgo, and Capricorn.', tag: 'Element Guide' },
  'air-signs-guide': { title: 'Air Signs Complete Guide: Gemini, Libra, Aquarius', description: 'Discover the Air element with detailed profiles of Gemini, Libra, and Aquarius.', tag: 'Element Guide' },
  'water-signs-guide': { title: 'Water Signs Complete Guide: Cancer, Scorpio, Pisces', description: 'Dive into the Water element with detailed profiles of Cancer, Scorpio, and Pisces.', tag: 'Element Guide' },
  'love-compatibility-guide': { title: 'Love Compatibility by Zodiac Sign Guide', description: 'Best love matches for all 12 signs, love languages by element.', tag: 'Love & Relationships' },
  'moon-phases-guide': { title: 'Moon Phases and Their Meanings Guide', description: 'All 8 lunar phases explained with birth moon phase personality.', tag: 'Reference' },
  'name-numerology-guide': { title: 'Name Numerology: The Power of Numbers in Your Name', description: 'Pythagorean system, core name numbers, baby naming, and business numerology.', tag: 'Numerology' },
  'career-astrology-guide': { title: 'Career Astrology: Find Your Ideal Career by Sign', description: 'Career strengths for all 12 signs and element work styles.', tag: 'Career' },
  'friendship-compatibility-guide': { title: 'Friendship Compatibility by Zodiac Sign Guide', description: 'Best friend matches for all 12 signs and element group dynamics.', tag: 'Compatibility' },
  'jupiter-saturn-guide': { title: 'Understanding Jupiter and Saturn in Your Chart', description: 'Jupiter and Saturn through all 12 signs and their role in personal growth.', tag: 'Guide' },
  'saturn-return-guide': { title: 'Saturn Return Survival Guide', description: 'What Saturn return is and practical strategies for navigating this life transition.', tag: 'Life Transitions' },
  'retrograde-planets-guide': { title: 'Retrograde Planets Complete Guide', description: 'Understanding Mercury, Venus, Mars, Jupiter, Saturn retrogrades with practical tips.', tag: 'Planetary Transits' },
};

export const allToolSlugList = Object.keys(toolSlugs);
export const allArticleSlugList = Object.keys(articleSlugs);
